# Generated by Django 4.0.4 on 2022-05-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
